"""Locked P08 learner, label-strategy, and cost-sensitive design.

The protocol separates five distinct objects:

1. latent truth generated by the simulation DGP;
2. feasible observed labels and verification;
3. label/observation strategy;
4. predictive learner;
5. training and evaluation cost regimes.

Cost-sensitive learning changes training weights. Cost-sensitive evaluation
changes decision thresholds, classification cost, and budget-constrained
review utility. Neither is allowed to use latent truth during training or
threshold selection.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
import importlib.util
from typing import cast

from core.semantic_keys import LEARNER_ID, METHOD_ID

LABEL_STRATEGY_ID = "label_strategy_id"
LEARNER_TIER = "learner_tier"
METHOD_FAMILY = "method_family"
TRAINING_COST_REGIME_ID = "training_cost_regime_id"
IMBALANCE_TREATMENT_ID = "imbalance_treatment_id"
REQUIRED_METRICS = "required_metrics"
EVALUATION_TARGETS = "evaluation_targets"
ANALYSIS_ROLE = "analysis_role"
EXECUTION_PROFILE = "execution_profile"
AVAILABLE_PROFILES = "available_profiles"
PROTOCOL_STATUS = "protocol_status"
IS_ACTIVE = "is_active"

LABEL_STRATEGIES: dict[str, dict[str, object]] = {
    "naive_observed_as_negative": {
        "description": "Treat every non-positive or unobserved row as negative.",
        "chapter_2_role": "conventional_contaminated_label_baseline",
    },
    "verified_only": {
        "description": "Fit only rows for which the feasible label is observed.",
        "chapter_2_role": "complete_case_baseline",
    },
    "ipw": {
        "description": "Fit verified rows with inverse verification-propensity weights.",
        "chapter_2_role": "selection_adjustment",
    },
    "pu": {
        "description": "Treat known positives as positive and all remaining rows as unlabeled.",
        "chapter_2_role": "positive_unlabeled_learning",
    },
}

CORE_LEARNERS: dict[str, dict[str, object]] = {
    "logistic_regression": {
        "family": "linear_probabilistic",
        "chapter_2_role": "vietnamese_historical_interpretable_baseline",
    },
    "linear_svm": {
        "family": "maximum_margin_linear",
        "chapter_2_role": "vietnamese_maximum_margin_benchmark",
    },
    "random_forest": {
        "family": "bagged_tree_ensemble",
        "chapter_2_role": "vietnamese_confirmatory_bagging_learner",
    },
    "xgboost": {
        "family": "gradient_boosted_trees",
        "chapter_2_role": "vietnamese_confirmatory_boosting_learner",
        "optional_dependency": "xgboost",
    },
    "multilayer_perceptron": {
        "family": "feedforward_neural_network",
        "chapter_2_role": "vietnamese_ann_family_benchmark",
    },
}

METHODOLOGICAL_LEARNERS: dict[str, dict[str, object]] = {
    "elastic_net_logistic": {
        "family": "regularized_linear_probabilistic",
        "chapter_2_role": "regularization_robustness",
    },
    "decision_tree": {
        "family": "single_tree",
        "chapter_2_role": "transparent_nonlinear_robustness",
    },
    "main_boosting": {
        "family": "histogram_gradient_boosting",
        "chapter_2_role": "generic_boosting_implementation_robustness",
    },
}

EXTENDED_LEARNERS: dict[str, dict[str, object]] = {
    "rbf_svm": {
        "family": "maximum_margin_kernel",
        "chapter_2_role": "algorithmic_breadth",
    },
    "k_nearest_neighbors": {
        "family": "instance_based",
        "chapter_2_role": "algorithmic_breadth",
    },
    "gaussian_naive_bayes": {
        "family": "generative_probabilistic",
        "chapter_2_role": "algorithmic_breadth",
    },
    "adaboost": {
        "family": "adaptive_boosting",
        "chapter_2_role": "algorithmic_breadth",
    },
    "extra_trees": {
        "family": "extremely_randomized_trees",
        "chapter_2_role": "algorithmic_breadth",
    },
    "lightgbm": {
        "family": "leafwise_gradient_boosted_trees",
        "chapter_2_role": "algorithmic_breadth",
        "optional_dependency": "lightgbm",
    },
    "catboost": {
        "family": "ordered_gradient_boosted_trees",
        "chapter_2_role": "algorithmic_breadth",
        "optional_dependency": "catboost",
    },
}

ALL_LEARNERS = {**CORE_LEARNERS, **METHODOLOGICAL_LEARNERS, **EXTENDED_LEARNERS}
CORE_STRATEGIES = tuple(LABEL_STRATEGIES)
NONCORE_STRATEGIES = ("naive_observed_as_negative", "pu")

IMBALANCE_TREATMENTS: dict[str, dict[str, object]] = {
    "none": {
        "description": "No synthetic class rebalancing.",
        "role": "reference_no_resampling",
    },
    "smote": {
        "description": "Synthetic Minority Oversampling Technique on feasible supervised labels.",
        "role": "vietnamese_literature_imbalance_robustness",
    },
    "adasyn": {
        "description": "Adaptive synthetic oversampling on feasible supervised labels.",
        "role": "vietnamese_literature_imbalance_robustness",
    },
}

STANDALONE_ESTIMATORS: dict[str, dict[str, object]] = {
    "latent_bayesian": {
        "description": "Latent prevalence/measurement estimator.",
        "chapter_2_role": "probabilistic_ml_latent_model",
    },
    "partial_identification": {
        "description": "Sensitivity-bounded identified set.",
        "chapter_2_role": "partial_identification",
    },
}

DEFAULT_COST_REGIMES: tuple[dict[str, object], ...] = (
    {
        "cost_regime_id": "symmetric",
        "false_positive_cost": 1.0,
        "false_negative_cost": 1.0,
        "review_cost": 0.0,
        "true_positive_benefit": 0.0,
        "role": "cost_neutral_baseline",
    },
    {
        "cost_regime_id": "moderate_fn",
        "false_positive_cost": 1.0,
        "false_negative_cost": 5.0,
        "review_cost": 0.10,
        "true_positive_benefit": 0.0,
        "role": "moderate_false_negative_penalty",
    },
    {
        "cost_regime_id": "high_fn",
        "false_positive_cost": 1.0,
        "false_negative_cost": 20.0,
        "review_cost": 0.10,
        "true_positive_benefit": 0.0,
        "role": "high_false_negative_penalty",
    },
    {
        "cost_regime_id": "extreme_fn",
        "false_positive_cost": 1.0,
        "false_negative_cost": 50.0,
        "review_cost": 0.10,
        "true_positive_benefit": 0.0,
        "role": "extreme_false_negative_stress",
    },
)

DEFAULT_REVIEW_BUDGETS: tuple[dict[str, object], ...] = (
    {"review_budget_id": "top_01pct", "fraction": 0.01},
    {"review_budget_id": "top_05pct", "fraction": 0.05},
    {"review_budget_id": "top_10pct", "fraction": 0.10},
)

BASE_PREDICTIVE_REQUIRED_METRICS = (
    "fit_success",
    "source_training_rows",
    "training_rows",
    "training_positive_rate",
    "post_resampling_positive_rate",
    "imbalance_treatment_applied",
    "synthetic_rows_added",
    "selected_threshold",
    "threshold_selection_success",
    "training_cost_weight_mean",
    "training_cost_weight_max",
    "observed_average_precision",
    "latent_average_precision",
    "latent_auc",
    "latent_brier",
    "latent_precision_at_k",
    "observed_minus_latent_ap",
    "verification_rate",
    "maturity_rate",
    "realized_prevalence",
    "latent_probability_mean",
    "empirical_panel_rows",
    "empirical_observed_positive_rate",
    "empirical_known_label_rate",
    "calibrated_latent_prevalence",
)

THRESHOLD_COST_METRICS = (
    "total_cost",
    "cost_per_firm",
    "normalized_cost_regret",
    "cost_savings_vs_all_negative",
    "cost_regret_vs_oracle",
    "false_negative_component",
    "false_positive_component",
    "review_component",
)

BUDGET_COST_METRICS = (
    "total_cost",
    "normalized_cost_regret",
    "cost_savings_vs_all_negative",
    "cost_regret_vs_oracle",
    "precision",
    "recall",
)

STANDALONE_REQUIRED_METRICS = (
    "fit_success",
    "prevalence_error",
    "prevalence_squared_error",
    "prevalence_coverage",
    "interval_width",
    "empirical_panel_rows",
    "empirical_observed_positive_rate",
    "empirical_known_label_rate",
    "calibrated_latent_prevalence",
)

PREDICTIVE_EVALUATION_TARGETS = (
    "observed_label",
    "latent_truth",
    "latent_cost",
)
STANDALONE_EVALUATION_TARGETS = ("latent_parameter",)


def build_cost_sensitive_contract(simulation: Mapping[str, object]) -> dict[str, object]:
    raw = simulation.get("cost_sensitive")
    if not isinstance(raw, dict):
        raise ValueError("simulation.cost_sensitive mapping is required")
    settings = cast(dict[str, object], raw)
    if settings.get("enabled") is not True:
        raise ValueError("simulation.cost_sensitive.enabled must be true")

    regimes_raw = settings.get("cost_regimes")
    if not isinstance(regimes_raw, list) or not regimes_raw:
        raise ValueError("simulation.cost_sensitive.cost_regimes must be nonempty")
    regimes: list[dict[str, object]] = []
    seen_regimes: set[str] = set()
    for index, item in enumerate(regimes_raw):
        if not isinstance(item, dict):
            raise ValueError(f"cost regime {index}: mapping required")
        regime = cast(dict[str, object], item)
        regime_id = str(regime.get("cost_regime_id", ""))
        if not regime_id or regime_id in seen_regimes:
            raise ValueError("cost_regime_id must be unique and nonempty")
        seen_regimes.add(regime_id)
        normalized = {"cost_regime_id": regime_id}
        for field in (
            "false_positive_cost",
            "false_negative_cost",
            "review_cost",
            "true_positive_benefit",
        ):
            value = regime.get(field)
            if not isinstance(value, (int, float)) or float(value) < 0:
                raise ValueError(f"cost regime={regime_id}: {field} must be nonnegative")
            normalized[field] = float(value)
        if normalized["false_positive_cost"] <= 0 or normalized["false_negative_cost"] <= 0:
            raise ValueError(
                f"cost regime={regime_id}: false-positive and false-negative costs must be positive"
            )
        normalized["role"] = str(regime.get("role", "sensitivity"))
        regimes.append(normalized)

    core_training = _registered_ids(
        settings.get("core_training_regimes"),
        "simulation.cost_sensitive.core_training_regimes",
        seen_regimes,
    )
    extended_training = _registered_ids(
        settings.get("extended_training_regimes"),
        "simulation.cost_sensitive.extended_training_regimes",
        seen_regimes,
    )
    evaluation = _registered_ids(
        settings.get("evaluation_regimes"),
        "simulation.cost_sensitive.evaluation_regimes",
        seen_regimes,
    )
    neutral_id = str(settings.get("cost_neutral_regime_id", ""))
    if neutral_id not in seen_regimes:
        raise ValueError("cost_neutral_regime_id must reference a registered regime")
    if neutral_id not in core_training or neutral_id not in extended_training:
        raise ValueError("cost-neutral regime must be included in both training blocks")

    budgets_raw = settings.get("review_budgets")
    if not isinstance(budgets_raw, list) or not budgets_raw:
        raise ValueError("simulation.cost_sensitive.review_budgets must be nonempty")
    budgets: list[dict[str, object]] = []
    seen_budgets: set[str] = set()
    for index, item in enumerate(budgets_raw):
        if not isinstance(item, dict):
            raise ValueError(f"review budget {index}: mapping required")
        budget = cast(dict[str, object], item)
        budget_id = str(budget.get("review_budget_id", ""))
        fraction = budget.get("fraction")
        if not budget_id or budget_id in seen_budgets:
            raise ValueError("review_budget_id must be unique and nonempty")
        if not isinstance(fraction, (int, float)) or not 0 < float(fraction) <= 1:
            raise ValueError(f"review budget={budget_id}: fraction must be in (0,1]")
        seen_budgets.add(budget_id)
        budgets.append({"review_budget_id": budget_id, "fraction": float(fraction)})

    validation_fraction = settings.get("threshold_validation_fraction", 0.25)
    if not isinstance(validation_fraction, (int, float)) or not 0.10 <= float(validation_fraction) <= 0.50:
        raise ValueError("threshold_validation_fraction must be in [0.10,0.50]")
    maximum_cost_weight = settings.get("maximum_cost_weight", 100.0)
    if not isinstance(maximum_cost_weight, (int, float)) or float(maximum_cost_weight) < 1:
        raise ValueError("maximum_cost_weight must be >= 1")
    cost_mcse_relative_fraction = settings.get("cost_mcse_relative_fraction", 0.02)
    if (
        not isinstance(cost_mcse_relative_fraction, (int, float))
        or not 0 < float(cost_mcse_relative_fraction) <= 0.25
    ):
        raise ValueError("cost_mcse_relative_fraction must be in (0,0.25]")

    return {
        "contract_version": 4,
        "cost_regime_registry": regimes,
        "core_training_regime_ids": core_training,
        "extended_training_regime_ids": extended_training,
        "evaluation_regime_ids": evaluation,
        "cost_neutral_regime_id": neutral_id,
        "review_budget_registry": budgets,
        "primary_evaluation_cost_regime_id": _registered_id(
            settings.get("primary_evaluation_cost_regime_id"),
            "primary_evaluation_cost_regime_id",
            seen_regimes,
        ),
        "primary_review_budget_id": _registered_id(
            settings.get("primary_review_budget_id"),
            "primary_review_budget_id",
            seen_budgets,
        ),
        "threshold_validation_fraction": float(validation_fraction),
        "maximum_cost_weight": float(maximum_cost_weight),
        "cost_mcse_relative_fraction": float(cost_mcse_relative_fraction),
        "class_weight_rule": "positive=FN_cost+TP_benefit; negative=FP_cost",
        "ipw_combination_rule": "normalized(IPW * class_cost_weight)",
        "unsupported_sample_weight_rule": "weighted_bootstrap",
        "threshold_selection_rule": "minimize_weighted_feasible_validation_cost",
        "threshold_refit_rule": "select_on_validation_then_refit_on_full_training",
        "latent_truth_training_forbidden": True,
    }



def build_imbalance_treatment_contract(simulation: Mapping[str, object]) -> dict[str, object]:
    raw = simulation.get("imbalance_treatment")
    if not isinstance(raw, dict):
        raise ValueError("simulation.imbalance_treatment mapping is required")
    settings = cast(dict[str, object], raw)
    if settings.get("enabled") is not True:
        raise ValueError("simulation.imbalance_treatment.enabled must be true")

    treatment_ids = _registered_ids(
        settings.get("treatments"),
        "simulation.imbalance_treatment.treatments",
        set(IMBALANCE_TREATMENTS),
    )
    neutral_id = str(settings.get("neutral_treatment_id", ""))
    if neutral_id != "none" or neutral_id not in treatment_ids:
        raise ValueError("neutral_treatment_id must be registered as none")
    robustness_ids = _registered_ids(
        settings.get("robustness_treatments"),
        "simulation.imbalance_treatment.robustness_treatments",
        set(treatment_ids),
    )
    if neutral_id in robustness_ids:
        raise ValueError("robustness_treatments must exclude none")
    learners = _registered_ids(
        settings.get("learners"),
        "simulation.imbalance_treatment.learners",
        set(ALL_LEARNERS),
    )
    strategies = _registered_ids(
        settings.get("strategies"),
        "simulation.imbalance_treatment.strategies",
        set(LABEL_STRATEGIES),
    )
    if set(strategies) - {"naive_observed_as_negative", "verified_only"}:
        raise ValueError("SMOTE/ADASYN are restricted to naive and verified-only labels")
    training_cost_regime_id = str(settings.get("training_cost_regime_id", ""))
    if training_cost_regime_id != "symmetric":
        raise ValueError("imbalance-treatment robustness must use symmetric training cost")
    maximum_neighbors = settings.get("maximum_neighbors", 5)
    if not isinstance(maximum_neighbors, int) or maximum_neighbors < 1:
        raise ValueError("imbalance_treatment.maximum_neighbors must be a positive integer")

    return {
        "contract_version": 6,
        "treatment_registry": [
            {"imbalance_treatment_id": item, **dict(IMBALANCE_TREATMENTS[item])}
            for item in treatment_ids
        ],
        "neutral_treatment_id": neutral_id,
        "robustness_treatment_ids": robustness_ids,
        "robustness_learner_ids": learners,
        "robustness_strategy_ids": strategies,
        "training_cost_regime_id": training_cost_regime_id,
        "maximum_neighbors": int(maximum_neighbors),
        "latent_truth_for_resampling_forbidden": True,
        "pu_or_ipw_resampling_forbidden": True,
        "validation_resampling_forbidden": True,
    }

def build_full_method_registry(
    simulation: Mapping[str, object],
    cost_contract: Mapping[str, object] | None = None,
    imbalance_contract: Mapping[str, object] | None = None,
) -> list[dict[str, object]]:
    """Build the complete reusable library before profile activation."""
    enabled_strategies = _string_sequence(simulation.get("methods"), "simulation.methods")
    enabled_learners = _string_sequence(simulation.get("learners"), "simulation.learners")
    contract = dict(cost_contract or build_cost_sensitive_contract(simulation))
    imbalance = dict(
        imbalance_contract or build_imbalance_treatment_contract(simulation)
    )

    legacy_methods = {"observability_only", "content_only", "full", "anchor_pu"}
    present_legacy = sorted(set(enabled_strategies) & legacy_methods)
    if present_legacy:
        raise ValueError(f"P08 legacy fixed-score methods are forbidden: {present_legacy}")

    required_strategies = set(LABEL_STRATEGIES) | set(STANDALONE_ESTIMATORS)
    errors: list[str] = []
    missing_strategies = sorted(required_strategies - set(enabled_strategies))
    unknown_strategies = sorted(set(enabled_strategies) - required_strategies)
    missing_learners = sorted(set(ALL_LEARNERS) - set(enabled_learners))
    unknown_learners = sorted(set(enabled_learners) - set(ALL_LEARNERS))
    if missing_strategies:
        errors.append(f"missing methods={missing_strategies}")
    if unknown_strategies:
        errors.append(f"unknown methods={unknown_strategies}")
    if missing_learners:
        errors.append(f"missing learners={missing_learners}")
    if unknown_learners:
        errors.append(f"unknown learners={unknown_learners}")
    if errors:
        raise ValueError("P08 roster is incomplete: " + "; ".join(errors))

    required_metrics = predictive_required_metrics(contract)
    core_costs = [str(item) for item in cast(list[object], contract["core_training_regime_ids"])]
    noncore_costs = [
        str(item) for item in cast(list[object], contract["extended_training_regime_ids"])
    ]
    neutral_treatment = str(imbalance["neutral_treatment_id"])

    registry: list[dict[str, object]] = []
    for learner_id, learner in CORE_LEARNERS.items():
        for strategy_id in CORE_STRATEGIES:
            for cost_regime_id in core_costs:
                registry.append(
                    _predictive_method(
                        strategy_id=strategy_id,
                        learner_id=learner_id,
                        learner=learner,
                        learner_tier="core",
                        training_cost_regime_id=cost_regime_id,
                        imbalance_treatment_id=neutral_treatment,
                        required_metrics=required_metrics,
                    )
                )

    for tier, learner_group in (
        ("methodological", METHODOLOGICAL_LEARNERS),
        ("extended", EXTENDED_LEARNERS),
    ):
        for learner_id, learner in learner_group.items():
            for strategy_id in NONCORE_STRATEGIES:
                for cost_regime_id in noncore_costs:
                    registry.append(
                        _predictive_method(
                            strategy_id=strategy_id,
                            learner_id=learner_id,
                            learner=learner,
                            learner_tier=tier,
                            training_cost_regime_id=cost_regime_id,
                            imbalance_treatment_id=neutral_treatment,
                            required_metrics=required_metrics,
                        )
                    )

    treatment_ids = [
        str(item) for item in cast(list[object], imbalance["robustness_treatment_ids"])
    ]
    for learner_id in cast(list[str], imbalance["robustness_learner_ids"]):
        learner = ALL_LEARNERS[learner_id]
        for strategy_id in cast(list[str], imbalance["robustness_strategy_ids"]):
            for treatment_id in treatment_ids:
                registry.append(
                    _predictive_method(
                        strategy_id=strategy_id,
                        learner_id=learner_id,
                        learner=learner,
                        learner_tier="core",
                        training_cost_regime_id=str(imbalance["training_cost_regime_id"]),
                        imbalance_treatment_id=treatment_id,
                        required_metrics=required_metrics,
                    )
                )

    for estimator_id, estimator in STANDALONE_ESTIMATORS.items():
        registry.append(
            {
                METHOD_ID: estimator_id,
                LABEL_STRATEGY_ID: estimator_id,
                LEARNER_ID: "none",
                LEARNER_TIER: "standalone",
                TRAINING_COST_REGIME_ID: "not_applicable",
                IMBALANCE_TREATMENT_ID: "not_applicable",
                METHOD_FAMILY: "standalone_estimator",
                "estimator": dict(estimator),
                REQUIRED_METRICS: list(STANDALONE_REQUIRED_METRICS),
                EVALUATION_TARGETS: list(STANDALONE_EVALUATION_TARGETS),
            }
        )

    ids = [str(item[METHOD_ID]) for item in registry]
    if len(ids) != len(set(ids)):
        raise ValueError("P08 method_id values must be unique")
    return registry

def build_execution_profile_contract(
    simulation: Mapping[str, object],
    full_registry: Sequence[Mapping[str, object]],
) -> dict[str, object]:
    """Resolve config-locked execution profiles against the full method library."""
    raw_profiles = simulation.get("execution_profiles")
    if not isinstance(raw_profiles, dict) or not raw_profiles:
        raise ValueError("simulation.execution_profiles mapping is required")
    profiles = cast(dict[str, object], raw_profiles)
    active_profile = str(simulation.get("active_profile", ""))
    if not active_profile or active_profile not in profiles:
        raise ValueError("simulation.active_profile must reference execution_profiles")

    full_ids = {str(item[METHOD_ID]) for item in full_registry}
    if not full_ids:
        raise ValueError("P08 full method registry must be nonempty")
    by_id = {str(item[METHOD_ID]): dict(item) for item in full_registry}
    resolved: dict[str, set[str]] = {}
    resolving: set[str] = set()
    profile_rows: list[dict[str, object]] = []

    def resolve(profile_id: str) -> set[str]:
        if profile_id in resolved:
            return set(resolved[profile_id])
        if profile_id in resolving:
            raise ValueError(f"execution profile cycle detected at {profile_id}")
        raw = profiles.get(profile_id)
        if not isinstance(raw, dict):
            raise ValueError(f"execution profile={profile_id}: mapping required")
        spec = cast(dict[str, object], raw)
        resolving.add(profile_id)
        selected: set[str] = set()

        if spec.get("include_all_registered_methods") is True:
            selected.update(full_ids)

        unions_raw = spec.get("union_profiles", [])
        if unions_raw:
            if not isinstance(unions_raw, list):
                raise ValueError(f"execution profile={profile_id}: union_profiles must be a list")
            for parent in cast(list[object], unions_raw):
                parent_id = str(parent)
                if parent_id not in profiles:
                    raise ValueError(
                        f"execution profile={profile_id}: unknown union profile={parent_id}"
                    )
                selected.update(resolve(parent_id))

        blocks_raw = spec.get("blocks", [])
        if blocks_raw:
            if not isinstance(blocks_raw, list):
                raise ValueError(f"execution profile={profile_id}: blocks must be a list")
            for block_index, raw_block in enumerate(cast(list[object], blocks_raw)):
                if not isinstance(raw_block, dict):
                    raise ValueError(
                        f"execution profile={profile_id} block={block_index}: mapping required"
                    )
                block = cast(dict[str, object], raw_block)
                learner_ids = set(
                    _registered_ids(
                        block.get("learners"),
                        f"execution profile={profile_id}.blocks[{block_index}].learners",
                        set(ALL_LEARNERS),
                    )
                )
                strategy_ids = set(
                    _registered_ids(
                        block.get("strategies"),
                        f"execution profile={profile_id}.blocks[{block_index}].strategies",
                        set(LABEL_STRATEGIES),
                    )
                )
                allowed_cost_ids = {
                    str(method[TRAINING_COST_REGIME_ID])
                    for method in by_id.values()
                    if method.get(METHOD_FAMILY) == "predictive"
                }
                cost_ids = set(
                    _registered_ids(
                        block.get("training_cost_regimes"),
                        f"execution profile={profile_id}.blocks[{block_index}].training_cost_regimes",
                        allowed_cost_ids,
                    )
                )
                allowed_treatment_ids = {
                    str(method[IMBALANCE_TREATMENT_ID])
                    for method in by_id.values()
                    if method.get(METHOD_FAMILY) == "predictive"
                }
                treatment_values = block.get("imbalance_treatments", ["none"])
                treatment_ids = set(
                    _registered_ids(
                        treatment_values,
                        f"execution profile={profile_id}.blocks[{block_index}].imbalance_treatments",
                        allowed_treatment_ids,
                    )
                )
                for method_id, method in by_id.items():
                    if method.get(METHOD_FAMILY) != "predictive":
                        continue
                    if (
                        str(method[LEARNER_ID]) in learner_ids
                        and str(method[LABEL_STRATEGY_ID]) in strategy_ids
                        and str(method[TRAINING_COST_REGIME_ID]) in cost_ids
                        and str(method[IMBALANCE_TREATMENT_ID]) in treatment_ids
                    ):
                        selected.add(method_id)

        if spec.get("include_standalone_estimators") is True:
            selected.update(
                method_id
                for method_id, method in by_id.items()
                if method.get(METHOD_FAMILY) == "standalone_estimator"
            )

        resolving.remove(profile_id)
        if not selected:
            raise ValueError(f"execution profile={profile_id}: resolved method set is empty")
        unknown = sorted(selected - full_ids)
        if unknown:
            raise ValueError(f"execution profile={profile_id}: unknown methods={unknown}")
        resolved[profile_id] = set(selected)
        return set(selected)

    # Resolve in configuration order. This order, plus role_priority, is protocol-locked.
    for order, (profile_id, raw) in enumerate(profiles.items()):
        if not isinstance(raw, dict):
            raise ValueError(f"execution profile={profile_id}: mapping required")
        spec = cast(dict[str, object], raw)
        role = str(spec.get("analysis_role", ""))
        if not role:
            raise ValueError(f"execution profile={profile_id}: analysis_role required")
        priority_raw = spec.get("role_priority", order)
        if not isinstance(priority_raw, int) or priority_raw < 0:
            raise ValueError(f"execution profile={profile_id}: role_priority must be nonnegative")
        method_ids = sorted(resolve(profile_id))
        profile_rows.append(
            {
                "profile_id": profile_id,
                ANALYSIS_ROLE: role,
                "role_priority": int(priority_raw),
                "method_ids": method_ids,
                "method_count": len(method_ids),
                "description": str(spec.get("description", "")),
            }
        )

    uncovered = sorted(
        full_ids - set().union(*(set(cast(list[str], row["method_ids"])) for row in profile_rows))
    )
    if uncovered:
        raise ValueError(
            "All registered methods must belong to at least one execution profile; "
            f"uncovered={uncovered}"
        )

    active_row = next(row for row in profile_rows if row["profile_id"] == active_profile)
    return {
        "contract_version": 6,
        "active_profile": active_profile,
        "active_method_ids": list(cast(list[str], active_row["method_ids"])),
        "active_method_count": int(active_row["method_count"]),
        "profiles": profile_rows,
        "full_method_count": len(full_ids),
        "profile_selection_locked_by_config": True,
        "cli_override_must_match_config": True,
    }


def apply_execution_profile(
    full_registry: Sequence[Mapping[str, object]],
    profile_contract: Mapping[str, object],
) -> list[dict[str, object]]:
    """Annotate every available method while activating only the locked profile."""
    raw_profiles = profile_contract.get("profiles")
    if not isinstance(raw_profiles, list) or not raw_profiles:
        raise ValueError("profile contract profiles must be nonempty")
    profiles = [cast(dict[str, object], item) for item in raw_profiles if isinstance(item, dict)]
    active_profile = str(profile_contract.get("active_profile", ""))
    active_ids = {
        str(item) for item in cast(list[object], profile_contract.get("active_method_ids", []))
    }
    if not active_profile or not active_ids:
        raise ValueError("profile contract active profile and methods are required")

    output: list[dict[str, object]] = []
    for raw_method in full_registry:
        method = dict(raw_method)
        method_id = str(method[METHOD_ID])
        available = [
            str(profile["profile_id"])
            for profile in profiles
            if method_id in {str(item) for item in cast(list[object], profile["method_ids"])}
        ]
        if not available:
            raise ValueError(f"method={method_id}: no execution profile membership")

        role_candidates = [
            profile
            for profile in profiles
            if str(profile["profile_id"]) in available
            and str(profile["analysis_role"]) != "exploratory_full_benchmark"
        ]
        if not role_candidates:
            role_candidates = [
                profile for profile in profiles if str(profile["profile_id"]) in available
            ]
        role_profile = min(
            role_candidates,
            key=lambda item: (int(item["role_priority"]), str(item["profile_id"])),
        )
        role = str(role_profile["analysis_role"])
        active = method_id in active_ids
        if active:
            if role == "confirmatory":
                status = "PRE_SPECIFIED_ACTIVE"
            elif role.startswith("robustness"):
                status = "ROBUSTNESS_ACTIVE"
            else:
                status = "EXPLORATORY_ACTIVE"
        else:
            status = "AVAILABLE_NOT_ACTIVE"

        method[AVAILABLE_PROFILES] = available
        method[ANALYSIS_ROLE] = role
        method[EXECUTION_PROFILE] = active_profile
        method[PROTOCOL_STATUS] = status
        method[IS_ACTIVE] = active
        output.append(method)
    return output


def build_method_registry(
    simulation: Mapping[str, object],
    cost_contract: Mapping[str, object] | None = None,
    imbalance_contract: Mapping[str, object] | None = None,
) -> list[dict[str, object]]:
    """Build the full library and activate only the config-locked execution profile."""
    cost = dict(cost_contract or build_cost_sensitive_contract(simulation))
    imbalance = dict(
        imbalance_contract or build_imbalance_treatment_contract(simulation)
    )
    full_registry = build_full_method_registry(simulation, cost, imbalance)
    profile_contract = build_execution_profile_contract(simulation, full_registry)
    return apply_execution_profile(full_registry, profile_contract)

def predictive_required_metrics(cost_contract: Mapping[str, object]) -> list[str]:
    required = list(BASE_PREDICTIVE_REQUIRED_METRICS)
    evaluation_ids = [
        str(item) for item in cast(list[object], cost_contract["evaluation_regime_ids"])
    ]
    budgets = cast(list[dict[str, object]], cost_contract["review_budget_registry"])
    for regime_id in evaluation_ids:
        for metric in THRESHOLD_COST_METRICS:
            required.append(threshold_cost_metric_id(regime_id, metric))
        for budget in budgets:
            budget_id = str(budget["review_budget_id"])
            for metric in BUDGET_COST_METRICS:
                required.append(budget_cost_metric_id(budget_id, regime_id, metric))
    return required


def threshold_cost_metric_id(cost_regime_id: str, metric: str) -> str:
    return f"threshold_cost::{cost_regime_id}::{metric}"


def budget_cost_metric_id(review_budget_id: str, cost_regime_id: str, metric: str) -> str:
    return f"budget_cost::{review_budget_id}::{cost_regime_id}::{metric}"


def expected_counts(
    cost_contract: Mapping[str, object] | None = None,
    imbalance_contract: Mapping[str, object] | None = None,
) -> dict[str, int]:
    """Counts for the complete available method library."""
    core_cost_count = 3 if cost_contract is None else len(
        cast(list[object], cost_contract["core_training_regime_ids"])
    )
    noncore_cost_count = 2 if cost_contract is None else len(
        cast(list[object], cost_contract["extended_training_regime_ids"])
    )
    imbalance_count = 12 if imbalance_contract is None else (
        len(cast(list[object], imbalance_contract["robustness_learner_ids"]))
        * len(cast(list[object], imbalance_contract["robustness_strategy_ids"]))
        * len(cast(list[object], imbalance_contract["robustness_treatment_ids"]))
    )
    core = len(CORE_LEARNERS) * len(CORE_STRATEGIES) * core_cost_count
    methodological = (
        len(METHODOLOGICAL_LEARNERS) * len(NONCORE_STRATEGIES) * noncore_cost_count
    )
    extended = len(EXTENDED_LEARNERS) * len(NONCORE_STRATEGIES) * noncore_cost_count
    standalone = len(STANDALONE_ESTIMATORS)
    neutral_core = len(CORE_LEARNERS) * len(CORE_STRATEGIES)
    return {
        "core_cost_neutral_predictive": neutral_core,
        "core_cost_sensitive_predictive": core - neutral_core,
        "core_predictive": core,
        "methodological_predictive": methodological,
        "extended_predictive": extended,
        "imbalance_robustness_predictive": imbalance_count,
        "predictive_total": core + methodological + extended + imbalance_count,
        "standalone": standalone,
        "method_total": core + methodological + extended + imbalance_count + standalone,
        "learner_total": len(ALL_LEARNERS),
    }

def profile_expected_counts(
    registry: Sequence[Mapping[str, object]],
    *,
    active_only: bool = True,
) -> dict[str, object]:
    selected = [
        item for item in registry if not active_only or item.get(IS_ACTIVE) is True
    ]
    predictive = [item for item in selected if item.get(METHOD_FAMILY) == "predictive"]
    standalone = [
        item for item in selected if item.get(METHOD_FAMILY) == "standalone_estimator"
    ]
    learners = {
        str(item[LEARNER_ID])
        for item in predictive
        if str(item.get(LEARNER_ID, "")) not in {"", "none"}
    }
    role_counts: dict[str, int] = {}
    status_counts: dict[str, int] = {}
    for item in selected:
        role = str(item.get(ANALYSIS_ROLE, "unclassified"))
        status = str(item.get(PROTOCOL_STATUS, "unknown"))
        role_counts[role] = role_counts.get(role, 0) + 1
        status_counts[status] = status_counts.get(status, 0) + 1
    return {
        "predictive_total": len(predictive),
        "standalone": len(standalone),
        "method_total": len(selected),
        "learner_total": len(learners),
        "analysis_role_counts": role_counts,
        "protocol_status_counts": status_counts,
    }



def required_optional_dependencies(
    registry: Sequence[Mapping[str, object]],
    *,
    active_only: bool = True,
) -> set[str]:
    dependencies: set[str] = set()
    for item in registry:
        if active_only and item.get(IS_ACTIVE) is not True:
            continue
        learner = item.get("learner")
        if isinstance(learner, dict):
            dependency = learner.get("optional_dependency")
            if isinstance(dependency, str) and dependency:
                dependencies.add(dependency)
        if str(item.get(IMBALANCE_TREATMENT_ID, "none")) in {"smote", "adasyn"}:
            dependencies.add("imblearn")
    return dependencies


def validate_optional_dependencies(
    registry: Sequence[Mapping[str, object]],
    *,
    active_only: bool = True,
) -> list[str]:
    required = required_optional_dependencies(registry, active_only=active_only)
    missing = sorted(
        dependency
        for dependency in required
        if importlib.util.find_spec(dependency) is None
    )
    if missing:
        raise ValueError(f"P08 active profile is missing optional dependencies={missing}")
    return sorted(required)

def active_method_ids(scenario: Mapping[str, object]) -> set[str]:
    raw = scenario.get("active_method_ids")
    if isinstance(raw, list) and raw:
        return {str(item) for item in raw}
    registry = scenario.get("method_registry")
    if not isinstance(registry, list):
        raise ValueError("P08 scenario is missing method_registry")
    return {
        str(item[METHOD_ID])
        for item in registry
        if isinstance(item, dict) and item.get(IS_ACTIVE) is True
    }


def method_by_id(
    scenario: Mapping[str, object],
    method_id: str,
    *,
    require_active: bool = True,
) -> dict[str, object]:
    raw_registry = scenario.get("method_registry")
    if not isinstance(raw_registry, list):
        raise ValueError("P08 scenario is missing method_registry")
    matches = [
        cast(dict[str, object], item)
        for item in raw_registry
        if isinstance(item, dict) and item.get(METHOD_ID) == method_id
    ]
    if len(matches) != 1:
        raise ValueError(f"method={method_id}: exactly one registered method required")
    method = dict(matches[0])
    if require_active and method.get(IS_ACTIVE) is not True:
        raise ValueError(
            f"method={method_id}: method is available but inactive under "
            f"profile={method.get(EXECUTION_PROFILE)}"
        )
    return method

def cost_regime_by_id(scenario: Mapping[str, object], cost_regime_id: str) -> dict[str, object]:
    raw = scenario.get("cost_regime_registry")
    if not isinstance(raw, list):
        raise ValueError("P08 scenario is missing cost_regime_registry")
    matches = [
        cast(dict[str, object], item)
        for item in raw
        if isinstance(item, dict) and item.get("cost_regime_id") == cost_regime_id
    ]
    if len(matches) != 1:
        raise ValueError(f"cost_regime={cost_regime_id}: exactly one registered regime required")
    return dict(matches[0])


def evaluation_cost_regimes(scenario: Mapping[str, object]) -> list[dict[str, object]]:
    settings = scenario.get("cost_sensitive_settings")
    if not isinstance(settings, dict):
        raise ValueError("P08 scenario is missing cost_sensitive_settings")
    ids = settings.get("evaluation_regime_ids")
    if not isinstance(ids, list) or not ids:
        raise ValueError("P08 evaluation_regime_ids must be nonempty")
    return [cost_regime_by_id(scenario, str(item)) for item in ids]


def review_budgets(scenario: Mapping[str, object]) -> list[dict[str, object]]:
    raw = scenario.get("review_budget_registry")
    if not isinstance(raw, list) or not raw:
        raise ValueError("P08 scenario is missing review_budget_registry")
    return [dict(cast(dict[str, object], item)) for item in raw if isinstance(item, dict)]


def required_metric_ids(method_spec: Mapping[str, object]) -> set[str]:
    raw = method_spec.get(REQUIRED_METRICS)
    if not isinstance(raw, list) or not raw:
        raise ValueError("P08 method required_metrics must be a nonempty list")
    return {str(item) for item in raw}


def validate_batch_metric_presence(
    *, metric_ids: set[str], method_spec: Mapping[str, object]
) -> list[str]:
    return sorted(required_metric_ids(method_spec) - metric_ids)


def _predictive_method(
    *,
    strategy_id: str,
    learner_id: str,
    learner: Mapping[str, object],
    learner_tier: str,
    training_cost_regime_id: str,
    imbalance_treatment_id: str,
    required_metrics: list[str],
) -> dict[str, object]:
    base_id = f"{strategy_id}__{learner_id}"
    if imbalance_treatment_id != "none":
        base_id += f"__imbalance_{imbalance_treatment_id}"
    return {
        METHOD_ID: f"{base_id}__traincost_{training_cost_regime_id}",
        LABEL_STRATEGY_ID: strategy_id,
        LEARNER_ID: learner_id,
        LEARNER_TIER: learner_tier,
        TRAINING_COST_REGIME_ID: training_cost_regime_id,
        IMBALANCE_TREATMENT_ID: imbalance_treatment_id,
        METHOD_FAMILY: "predictive",
        "strategy": dict(LABEL_STRATEGIES[strategy_id]),
        "learner": dict(learner),
        "imbalance_treatment": dict(IMBALANCE_TREATMENTS[imbalance_treatment_id]),
        "cost_sensitive_training": training_cost_regime_id != "symmetric",
        REQUIRED_METRICS: list(required_metrics),
        EVALUATION_TARGETS: list(PREDICTIVE_EVALUATION_TARGETS),
    }

def _registered_ids(value: object, context: str, allowed: set[str]) -> list[str]:
    values = _string_sequence(value, context)
    unknown = sorted(set(values) - allowed)
    if unknown:
        raise ValueError(f"{context}: unknown ids={unknown}")
    return values


def _registered_id(value: object, context: str, allowed: set[str]) -> str:
    item = str(value or "")
    if item not in allowed:
        raise ValueError(f"{context}: registered id required")
    return item


def _string_sequence(value: object, context: str) -> list[str]:
    if not isinstance(value, list) or not value:
        raise ValueError(f"{context}: nonempty list required")
    values = [str(item) for item in cast(Sequence[object], value)]
    if any(not item for item in values) or len(values) != len(set(values)):
        raise ValueError(f"{context}: unique nonempty strings required")
    return values
