"""Central logical column identifiers; physical bindings remain registry-owned."""

AVAILABILITY_DATE = "availability_date"
CHANNEL_ID = "channel_id"
ELIGIBLE = "eligible"
ESTIMATE = "estimate"
FIRM_ID = "firm_id"
FISCAL_YEAR = "fiscal_year"
LEARNER_ID = "learner_id"
MATURE = "mature"
MCSE = "mcse"
MEASUREMENT_ID = "measurement_id"
METHOD_ID = "method_id"
METRIC_ID = "metric_id"
OUTCOME = "outcome"
OUTER_FOLD = "outer_fold"
PREDICTION = "prediction"
PREDICTION_TIME = "prediction_time"
REPLICATION_ID = "replication_id"
SCENARIO_ID = "scenario_id"
SOURCE_ID = "source_id"
TARGET_ID = "target_id"
WEIGHT = "weight"
