"""Partial-identification and robust model-selection primitives.

The functions in this module deliberately separate three objects:

* identified sets supported by observed data plus independently justified restrictions;
* sensitivity regions generated by maintained but unverified restrictions; and
* finite scenario envelopes used only for operational robustness summaries.

No function upgrades a sensitivity grid into an identified set merely because all
registered scenarios agree.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from math import isfinite
from typing import Any

IDENTIFIED_SET = "identified_set"
SENSITIVITY_REGION = "sensitivity_region"
SCENARIO_ENVELOPE = "scenario_envelope"


@dataclass(frozen=True)
class PrevalenceBounds:
    lower: float
    upper: float
    domain_type: str
    restrictions_used: tuple[str, ...]
    status: str

    def as_dict(self) -> dict[str, object]:
        return {
            "lower": self.lower,
            "upper": self.upper,
            "uncertainty_domain_type": self.domain_type,
            "restrictions_used": list(self.restrictions_used),
            "status": self.status,
        }


def prevalence_bounds(
    observed_positive_rate: float,
    *,
    false_positive_upper: float | None = None,
    sensitivity_lower: float | None = None,
    restrictions_independently_justified: bool = False,
) -> PrevalenceBounds:
    """Return conservative prevalence bounds for one observed proxy channel.

    Let ``p = P(S=1)`` and ``alpha = P(S=1 | Y*=0)``. If only
    ``alpha <= alpha_bar`` is maintained, then

    ``pi >= max(0, (p-alpha_bar)/(1-alpha_bar))``.

    A nontrivial upper bound additionally requires a lower bound on the reduced-form
    sensitivity ``P(S=1 | Y*=1)``. Restrictions are classified as an identified-set
    basis only when their independent justification is explicitly supplied.
    """

    p = _probability(observed_positive_rate, "observed_positive_rate")
    lower = 0.0
    upper = 1.0
    used: list[str] = []

    if false_positive_upper is not None:
        alpha = _probability(false_positive_upper, "false_positive_upper")
        if alpha >= 1.0:
            raise ValueError("false_positive_upper must be smaller than 1")
        lower = max(0.0, (p - alpha) / (1.0 - alpha))
        used.append("false_positive_upper")

    if sensitivity_lower is not None:
        sensitivity = _probability(sensitivity_lower, "sensitivity_lower")
        if sensitivity <= 0.0:
            raise ValueError("sensitivity_lower must be greater than 0")
        upper = min(1.0, p / sensitivity)
        used.append("sensitivity_lower")

    if lower > upper + 1e-12:
        return PrevalenceBounds(
            lower=lower,
            upper=upper,
            domain_type=(
                IDENTIFIED_SET if restrictions_independently_justified else SENSITIVITY_REGION
            ),
            restrictions_used=tuple(used),
            status="INCOMPATIBLE_RESTRICTIONS",
        )

    domain_type = (
        IDENTIFIED_SET if used and restrictions_independently_justified else SENSITIVITY_REGION
    )
    status = "BOUNDED" if used else "UNINFORMATIVE_WITHOUT_RESTRICTIONS"
    return PrevalenceBounds(
        lower=lower,
        upper=upper,
        domain_type=domain_type,
        restrictions_used=tuple(used),
        status=status,
    )


def paired_difference_dominance(
    metric_surface: Mapping[str, Mapping[str, float]],
    *,
    higher_is_better: bool = True,
    tolerance: float = 0.0,
) -> list[dict[str, object]]:
    """Evaluate uniform dominance using paired differences on common scenarios.

    Model ``a`` dominates model ``b`` when the worst paired difference across the
    common uncertainty domain is strictly above ``tolerance``. This is the primary
    dominance rule in Chapter 3 because both models are evaluated under the same
    admissible parameter configuration.
    """

    _validate_surface(metric_surface)
    models = sorted(metric_surface)
    rows: list[dict[str, object]] = []
    direction = 1.0 if higher_is_better else -1.0
    for model_a in models:
        for model_b in models:
            if model_a == model_b:
                continue
            common = sorted(set(metric_surface[model_a]) & set(metric_surface[model_b]))
            differences = [
                direction
                * (
                    float(metric_surface[model_a][scenario])
                    - float(metric_surface[model_b][scenario])
                )
                for scenario in common
            ]
            worst = min(differences) if differences else None
            rows.append(
                {
                    "model_a": model_a,
                    "model_b": model_b,
                    "common_configuration_count": len(common),
                    "worst_paired_difference": worst,
                    "dominates": worst is not None and worst > tolerance,
                }
            )
    return rows


def separated_range_dominance(
    metric_surface: Mapping[str, Mapping[str, float]],
    *,
    higher_is_better: bool = True,
    tolerance: float = 0.0,
) -> list[dict[str, object]]:
    """Evaluate the stronger separated-range dominance condition."""

    _validate_surface(metric_surface)
    models = sorted(metric_surface)
    rows: list[dict[str, object]] = []
    for model_a in models:
        values_a = [float(value) for value in metric_surface[model_a].values()]
        for model_b in models:
            if model_a == model_b:
                continue
            values_b = [float(value) for value in metric_surface[model_b].values()]
            if higher_is_better:
                margin = min(values_a) - max(values_b)
            else:
                margin = min(-value for value in values_a) - max(-value for value in values_b)
            rows.append(
                {
                    "model_a": model_a,
                    "model_b": model_b,
                    "separated_range_margin": margin,
                    "dominates": margin > tolerance,
                }
            )
    return rows


def model_selection_set(
    metric_surface: Mapping[str, Mapping[str, float]],
    *,
    higher_is_better: bool = True,
    tolerance: float = 0.0,
) -> list[str]:
    """Return models not uniformly dominated by another model."""

    dominance = paired_difference_dominance(
        metric_surface,
        higher_is_better=higher_is_better,
        tolerance=tolerance,
    )
    dominated = {str(row["model_b"]) for row in dominance if row["dominates"] is True}
    return sorted(set(metric_surface) - dominated)


def minimax_regret(
    metric_surface: Mapping[str, Mapping[str, float]],
    *,
    higher_is_better: bool = True,
) -> dict[str, object]:
    """Compute model-wise maximum regret and the minimax-regret set."""

    _validate_surface(metric_surface)
    common: set[str] | None = None
    for values in metric_surface.values():
        current = set(values)
        common = current if common is None else common & current
    scenarios = sorted(common or set())
    if not scenarios:
        return {
            "status": "INSUFFICIENT_COMMON_CONFIGURATIONS",
            "maximum_regret_by_model": {},
            "minimax_regret": None,
            "minimax_regret_set": [],
        }

    regrets: dict[str, float] = {}
    for model, values in metric_surface.items():
        model_regrets: list[float] = []
        for scenario in scenarios:
            scenario_values = [float(item[scenario]) for item in metric_surface.values()]
            value = float(values[scenario])
            if higher_is_better:
                model_regrets.append(max(scenario_values) - value)
            else:
                model_regrets.append(value - min(scenario_values))
        regrets[model] = max(model_regrets)

    minimum = min(regrets.values())
    selected = sorted(model for model, regret in regrets.items() if abs(regret - minimum) <= 1e-12)
    return {
        "status": "AVAILABLE",
        "common_configuration_count": len(scenarios),
        "maximum_regret_by_model": regrets,
        "minimax_regret": minimum,
        "minimax_regret_set": selected,
    }


def build_identification_summary(
    measurement_config: Mapping[str, Any],
    *,
    observed_positive_rate: float | None = None,
    metric_surface: Mapping[str, Mapping[str, float]] | None = None,
) -> dict[str, object]:
    """Build a fail-closed Chapter 3 identification summary.

    The configuration may register sensitivity values, but a restriction is treated
    as independently justified only when ``independent_justification_confirmed`` is
    true. This prevents an enforcement source name or legal status from silently
    becoming an identifying restriction.
    """

    raw_identification = measurement_config.get("identification")
    identification = dict(raw_identification) if isinstance(raw_identification, Mapping) else {}
    raw_restrictions = identification.get("restrictions")
    restrictions = dict(raw_restrictions) if isinstance(raw_restrictions, Mapping) else {}
    independently_justified = bool(identification.get("independent_justification_confirmed", False))

    false_positive_upper = _optional_probability(
        restrictions.get("enforcement_false_positive_upper"),
        "enforcement_false_positive_upper",
    )
    sensitivity_lower = _optional_probability(
        restrictions.get("enforcement_sensitivity_lower"),
        "enforcement_sensitivity_lower",
    )

    if observed_positive_rate is None:
        bounds = PrevalenceBounds(
            lower=0.0,
            upper=1.0,
            domain_type=SENSITIVITY_REGION,
            restrictions_used=tuple(),
            status="OBSERVED_POSITIVE_RATE_UNAVAILABLE",
        )
    else:
        bounds = prevalence_bounds(
            observed_positive_rate,
            false_positive_upper=false_positive_upper,
            sensitivity_lower=sensitivity_lower,
            restrictions_independently_justified=independently_justified,
        )

    result: dict[str, object] = {
        "status": (
            "IDENTIFIED_SET_AVAILABLE"
            if bounds.domain_type == IDENTIFIED_SET and bounds.status == "BOUNDED"
            else "SENSITIVITY_ONLY"
        ),
        "uncertainty_domain_type": bounds.domain_type,
        "prevalence_bounds": bounds.as_dict(),
        "high_specificity_anchor_assumed": False,
        "independent_justification_confirmed": independently_justified,
        "scenario_fraction_can_replace_identified_set_dominance": False,
    }

    if metric_surface:
        result["paired_difference_dominance"] = paired_difference_dominance(metric_surface)
        result["separated_range_dominance"] = separated_range_dominance(metric_surface)
        result["model_selection_set"] = model_selection_set(metric_surface)
        result["minimax_regret"] = minimax_regret(metric_surface)
    else:
        result.update(
            {
                "paired_difference_dominance": [],
                "separated_range_dominance": [],
                "model_selection_set": [],
                "minimax_regret": {
                    "status": "METRIC_SURFACE_UNAVAILABLE",
                    "maximum_regret_by_model": {},
                    "minimax_regret": None,
                    "minimax_regret_set": [],
                },
            }
        )
    return result


def _validate_surface(metric_surface: Mapping[str, Mapping[str, float]]) -> None:
    if not metric_surface:
        raise ValueError("metric_surface must contain at least one model")
    for model, values in metric_surface.items():
        if not isinstance(model, str) or not model:
            raise ValueError("model identifiers must be nonempty strings")
        if not values:
            raise ValueError(f"model={model}: at least one configuration is required")
        for scenario, value in values.items():
            if not isinstance(scenario, str) or not scenario:
                raise ValueError("configuration identifiers must be nonempty strings")
            if not isfinite(float(value)):
                raise ValueError(f"model={model}, configuration={scenario}: finite metric required")


def _probability(value: float, name: str) -> float:
    number = float(value)
    if not isfinite(number) or number < 0.0 or number > 1.0:
        raise ValueError(f"{name} must be a finite probability in [0, 1]")
    return number


def _optional_probability(value: object, name: str) -> float | None:
    if value is None:
        return None
    if not isinstance(value, (int, float)):
        raise ValueError(f"{name} must be numeric or null")
    return _probability(float(value), name)
